#!/usr/bin/env bash

# cloc --sql=res.sql ~/.racket/7.6/pkgs
# sqlite3 racketDB.db < res.sql
# dbeaver racketDB.db

# created with help of pup (https://github.com/ericchiang/pup)
# curl -s https://pkgs.racket-lang.org/index.html | pup 'table tr td.build_green a attr{href}' > instAllRacketPkgs.sh

raco pkg install --auto 1d6
raco pkg install --auto 2048
raco pkg install --auto 2htdp-typed
raco pkg install --auto _
raco pkg install --auto _-exp
raco pkg install --auto abnf
raco pkg install --auto acl2s-scribblings
raco pkg install --auto Adapton
raco pkg install --auto adjutor
raco pkg install --auto afl
raco pkg install --auto aful
raco pkg install --auto Agatha
raco pkg install --auto agile
raco pkg install --auto alexis-multicast
raco pkg install --auto alexis-util
raco pkg install --auto algebraic
raco pkg install --auto anaphoric
raco pkg install --auto anarki
raco pkg install --auto ansi
raco pkg install --auto ansi-color
raco pkg install --auto ANU-Web-Quantum-RNG
raco pkg install --auto aoc-racket
raco pkg install --auto appveyor-racket
raco pkg install --auto apse
raco pkg install --auto argo
raco pkg install --auto arguments
raco pkg install --auto arroy
raco pkg install --auto asi64
raco pkg install --auto asn1
raco pkg install --auto asn1-doc
raco pkg install --auto asn1-lib
raco pkg install --auto asn1-test
raco pkg install --auto asyncunit
raco pkg install --auto atomichron
raco pkg install --auto auto-syntax-e
raco pkg install --auto automata
raco pkg install --auto automata-doc
raco pkg install --auto automata-lib
raco pkg install --auto automata-test
raco pkg install --auto auxiliary-macro-context
raco pkg install --auto avl
raco pkg install --auto aws
raco pkg install --auto axe
raco pkg install --auto backport-template-pr1514
raco pkg install --auto base32
raco pkg install --auto basedir
raco pkg install --auto bazaar
raco pkg install --auto bcrypt
raco pkg install --auto beautiful-racket
raco pkg install --auto beautiful-racket-demo
raco pkg install --auto beautiful-racket-lib
raco pkg install --auto behavior
raco pkg install --auto bencode
raco pkg install --auto bencode-codec
raco pkg install --auto binary-class
raco pkg install --auto binary-class-dbf
raco pkg install --auto binary-class-exif
raco pkg install --auto binary-class-mp3
raco pkg install --auto binary-class-riff
raco pkg install --auto binaryio
raco pkg install --auto binaryio-lib
raco pkg install --auto binutils
raco pkg install --auto bitsyntax
raco pkg install --auto bloggy
raco pkg install --auto bluetooth-socket
raco pkg install --auto bnf
raco pkg install --auto bookcover
raco pkg install --auto br-parser-tools
raco pkg install --auto br-parser-tools-doc
raco pkg install --auto br-parser-tools-lib
raco pkg install --auto brag
raco pkg install --auto brag-lib
raco pkg install --auto brazilian-law
raco pkg install --auto brush
raco pkg install --auto buid
raco pkg install --auto bv
raco pkg install --auto bzip2
raco pkg install --auto c-utils
raco pkg install --auto calendar
raco pkg install --auto canonicalize-path
raco pkg install --auto casemate
raco pkg install --auto ccnum
raco pkg install --auto chain-module-begin
raco pkg install --auto charterm
raco pkg install --auto chess
raco pkg install --auto chez-runner
raco pkg install --auto chief
raco pkg install --auto chk-doc
raco pkg install --auto chk-lib
raco pkg install --auto choose-lang
raco pkg install --auto choose-out
raco pkg install --auto classicthesis-scribble
raco pkg install --auto cldr-bcp47
raco pkg install --auto cldr-core
raco pkg install --auto cldr-dates-modern
raco pkg install --auto cldr-localenames-modern
raco pkg install --auto cldr-numbers-modern
raco pkg install --auto collections
raco pkg install --auto collections-doc
raco pkg install --auto collections-lib
raco pkg install --auto collections-test
raco pkg install --auto colon-kw
raco pkg install --auto colon-match
raco pkg install --auto color-flood
raco pkg install --auto colormaps
raco pkg install --auto colors
raco pkg install --auto combinator-parser
raco pkg install --auto command-line-ext
raco pkg install --auto command-tree
raco pkg install --auto compact-annotations
raco pkg install --auto compiler-goodies
raco pkg install --auto component
raco pkg install --auto component-doc
raco pkg install --auto component-lib
raco pkg install --auto component-test
raco pkg install --auto compose-app
raco pkg install --auto cond-contract
raco pkg install --auto cond-strict
raco pkg install --auto continued-fractions
raco pkg install --auto contract-repl
raco pkg install --auto control
raco pkg install --auto country
raco pkg install --auto cover
raco pkg install --auto cover-cobertura
raco pkg install --auto cover-codecov
raco pkg install --auto cover-doc
raco pkg install --auto cover-lib
raco pkg install --auto cover-test
raco pkg install --auto cow-repl
raco pkg install --auto cpuinfo
raco pkg install --auto crc32c
raco pkg install --auto crypto
raco pkg install --auto crypto-doc
raco pkg install --auto crypto-lib
raco pkg install --auto crystal
raco pkg install --auto cs2500f16-jsonlab
raco pkg install --auto cs7480-util
raco pkg install --auto csp
raco pkg install --auto csrmesh
raco pkg install --auto css-expr
raco pkg install --auto css-tools
raco pkg install --auto csv-reading
raco pkg install --auto csv-writing
raco pkg install --auto cuecore
raco pkg install --auto cur
raco pkg install --auto cur-lib
raco pkg install --auto cur-test
raco pkg install --auto curly-fn
raco pkg install --auto curly-fn-doc
raco pkg install --auto curly-fn-lib
raco pkg install --auto curly-fn-test
raco pkg install --auto custom-load
raco pkg install --auto dali
raco pkg install --auto dan-scheme
raco pkg install --auto data-frame
raco pkg install --auto data-red-black
raco pkg install --auto database-url
raco pkg install --auto datacell
raco pkg install --auto datatype
raco pkg install --auto date
raco pkg install --auto dbus
raco pkg install --auto ddict
raco pkg install --auto debug-scopes
raco pkg install --auto decentralized-internet
raco pkg install --auto define-match-spread-out
raco pkg install --auto define-with-spec
raco pkg install --auto defpat
raco pkg install --auto delimit-app
raco pkg install --auto derp-3
raco pkg install --auto describe
raco pkg install --auto deta
raco pkg install --auto deta-doc
raco pkg install --auto deta-lib
raco pkg install --auto deta-test
raco pkg install --auto detail
raco pkg install --auto dherman-struct
raco pkg install --auto diagrama
raco pkg install --auto diagrama-doc
raco pkg install --auto diagrama-lib
raco pkg install --auto diagrams
raco pkg install --auto diff-merge
raco pkg install --auto disassemble
raco pkg install --auto disposable
raco pkg install --auto disposable-test
raco pkg install --auto distro-build
raco pkg install --auto distro-build-client
raco pkg install --auto distro-build-doc
raco pkg install --auto distro-build-lib
raco pkg install --auto distro-build-test
raco pkg install --auto dlm-read
raco pkg install --auto doc-coverage
raco pkg install --auto doodle
raco pkg install --auto dos
raco pkg install --auto dotenv
raco pkg install --auto dotlambda
raco pkg install --auto dracula-theme
raco pkg install --auto drcomplete
raco pkg install --auto drcomplete-auto
raco pkg install --auto drcomplete-base
raco pkg install --auto drcomplete-filename
raco pkg install --auto drcomplete-module
raco pkg install --auto drcomplete-required
raco pkg install --auto drcomplete-user-defined
raco pkg install --auto drdr
raco pkg install --auto drdr2
raco pkg install --auto drracket-ayu-mirage
raco pkg install --auto drracket-cyberpunk
raco pkg install --auto drracket-material
raco pkg install --auto drracket-scheme-dark-green
raco pkg install --auto drracket-solarized
raco pkg install --auto drracket-vim-tool
raco pkg install --auto drracket-zenburn
raco pkg install --auto DrRacketTheme
raco pkg install --auto dset
raco pkg install --auto dssl
raco pkg install --auto dssl2
raco pkg install --auto dynamic-ffi
raco pkg install --auto ebml
raco pkg install --auto ecmascript
raco pkg install --auto effection
raco pkg install --auto effection-doc
raco pkg install --auto effection-lib
raco pkg install --auto effection-test
raco pkg install --auto egal
raco pkg install --auto ejs
raco pkg install --auto emoji
raco pkg install --auto english
raco pkg install --auto envy
raco pkg install --auto esc-vp21
raco pkg install --auto eventfd
raco pkg install --auto exact-decimal-lang
raco pkg install --auto expander
raco pkg install --auto expect
raco pkg install --auto explorer
raco pkg install --auto extensible-functions
raco pkg install --auto extensible-parser-specifications
raco pkg install --auto fairyfloss
raco pkg install --auto Fairylog
raco pkg install --auto fancy-app
raco pkg install --auto fast-convert
raco pkg install --auto fector
raco pkg install --auto ffi-definer-convention
raco pkg install --auto ffmpeg-x86_64-macosx
raco pkg install --auto ffmpeg-x86_64-macosx-3-4
raco pkg install --auto fiberweb
raco pkg install --auto file-watchers
raco pkg install --auto finalizer
raco pkg install --auto find-parent-dir
raco pkg install --auto fixture
raco pkg install --auto flexpr
raco pkg install --auto fme
raco pkg install --auto fontland
raco pkg install --auto forged-ocelot
raco pkg install --auto forms
raco pkg install --auto forms-doc
raco pkg install --auto forms-lib
raco pkg install --auto forms-test
raco pkg install --auto forth
raco pkg install --auto fpbench
raco pkg install --auto fra
raco pkg install --auto fulmar
raco pkg install --auto functional
raco pkg install --auto functional-doc
raco pkg install --auto functional-lib
raco pkg install --auto Funktionuckelt
raco pkg install --auto futures-sort
raco pkg install --auto gcstats
raco pkg install --auto gdbdump
raco pkg install --auto gen-queue-lib
raco pkg install --auto generic-bind
raco pkg install --auto generic-syntax-expanders
raco pkg install --auto geoip
raco pkg install --auto geoip-doc
raco pkg install --auto geoip-lib
raco pkg install --auto get-pass
raco pkg install --auto get-primitive
raco pkg install --auto glm
raco pkg install --auto glossolalia
raco pkg install --auto gls
raco pkg install --auto gm-pepm-2018
raco pkg install --auto gmp
raco pkg install --auto gmp-lib
raco pkg install --auto gnucash
raco pkg install --auto google
raco pkg install --auto gradual-typing-bib
raco pkg install --auto graph
raco pkg install --auto graph-doc
raco pkg install --auto graph-lib
raco pkg install --auto graph-test
raco pkg install --auto gregor
raco pkg install --auto gregor-doc
raco pkg install --auto gregor-lib
raco pkg install --auto gregor-test
raco pkg install --auto gsl-integration
raco pkg install --auto gsl-rng
raco pkg install --auto gtp-benchmarks
raco pkg install --auto gtp-paper
raco pkg install --auto gtp-pict
raco pkg install --auto gtp-plot
raco pkg install --auto gtp-util
raco pkg install --auto gui-pkg-manager
raco pkg install --auto gui-pkg-manager-doc
raco pkg install --auto gui-widget-mixins
raco pkg install --auto haiku-enum
raco pkg install --auto hamt
raco pkg install --auto handy
raco pkg install --auto hive-client
raco pkg install --auto hive-common
raco pkg install --auto hive-server
raco pkg install --auto honu
raco pkg install --auto hostname
raco pkg install --auto htdp-json
raco pkg install --auto html-parsing
raco pkg install --auto html-template
raco pkg install --auto html-writing
raco pkg install --auto http
raco pkg install --auto http11
raco pkg install --auto http11-server
raco pkg install --auto http2
raco pkg install --auto hygienic-quote-lang
raco pkg install --auto hygienic-reader-extension
raco pkg install --auto hyper-literate
raco pkg install --auto hyphenate
raco pkg install --auto icfp2017-minikanren
raco pkg install --auto icns
raco pkg install --auto identikon
raco pkg install --auto impl-excl
raco pkg install --auto in-new-directory
raco pkg install --auto inexact-number-lang
raco pkg install --auto infix
raco pkg install --auto infix-syntax
raco pkg install --auto interactive-syntax
raco pkg install --auto interconfection
raco pkg install --auto interconfection-doc
raco pkg install --auto interconfection-lib
raco pkg install --auto interconfection-test
raco pkg install --auto intern
raco pkg install --auto ipoe
raco pkg install --auto iracket
raco pkg install --auto irc-client
raco pkg install --auto iswim
raco pkg install --auto jack-ease
raco pkg install --auto jack-posn
raco pkg install --auto java
raco pkg install --auto java-lexer
# raco pkg install --auto javascript
raco pkg install --auto jen
raco pkg install --auto jen-doc
raco pkg install --auto jen-lib
raco pkg install --auto jen-samples
raco pkg install --auto job-queue
raco pkg install --auto job-queue-doc
raco pkg install --auto job-queue-lib
raco pkg install --auto json-parsing
raco pkg install --auto json-pointer
raco pkg install --auto json-socket
raco pkg install --auto json-sourcery-lib
raco pkg install --auto json-type-provider
raco pkg install --auto k-infix
raco pkg install --auto kinda-ferpy
raco pkg install --auto kitco
raco pkg install --auto koyo
raco pkg install --auto koyo-doc
raco pkg install --auto koyo-lib
raco pkg install --auto koyo-north
raco pkg install --auto koyo-sentry
raco pkg install --auto kw-make-struct
raco pkg install --auto kw-make-struct-lib
raco pkg install --auto kw-utils
raco pkg install --auto lambda-calculus
raco pkg install --auto lang-file
raco pkg install --auto lang-file-lib
raco pkg install --auto latex-utils
raco pkg install --auto lathe-comforts
raco pkg install --auto lathe-comforts-doc
raco pkg install --auto lathe-comforts-lib
raco pkg install --auto lathe-comforts-test
raco pkg install --auto lathe-morphisms
raco pkg install --auto lathe-morphisms-doc
raco pkg install --auto lathe-morphisms-lib
raco pkg install --auto lathe-morphisms-test
raco pkg install --auto lathe-ordinals
raco pkg install --auto lathe-ordinals-doc
raco pkg install --auto lathe-ordinals-lib
raco pkg install --auto lathe-ordinals-test
raco pkg install --auto lazytree
raco pkg install --auto learn-to-type
raco pkg install --auto left-pad
raco pkg install --auto leftist-tree
raco pkg install --auto lens
raco pkg install --auto lens-common
raco pkg install --auto lens-data
raco pkg install --auto lens-doc
raco pkg install --auto lens-lib
raco pkg install --auto lens-unstable
raco pkg install --auto levenshtein
raco pkg install --auto libargon2
raco pkg install --auto libargon2-i386-win32
raco pkg install --auto libargon2-x86_64-linux
raco pkg install --auto libargon2-x86_64-macosx
raco pkg install --auto libargon2-x86_64-win32
raco pkg install --auto libgit2-x86_64-linux
raco pkg install --auto libgit2-x86_64-linux-natipkg
raco pkg install --auto libgit2-x86_64-macosx
raco pkg install --auto libkenji
raco pkg install --auto libsass-i386-win32
raco pkg install --auto libsass-x86_64-linux
raco pkg install --auto libsass-x86_64-macosx
raco pkg install --auto libsass-x86_64-win32
raco pkg install --auto libsqlite3-x86_64-linux
raco pkg install --auto libsqlite3-x86_64-macosx
raco pkg install --auto libuuid
raco pkg install --auto libvid-x86_64-macosx
raco pkg install --auto libxml2
raco pkg install --auto libxml2-x86_64-linux-natipkg
raco pkg install --auto linea
raco pkg install --auto list-util
raco pkg install --auto list-utils
raco pkg install --auto live-free-or-die
raco pkg install --auto loci
raco pkg install --auto logger
raco pkg install --auto logo
raco pkg install --auto loop
raco pkg install --auto lti-freq-domain-toolbox
raco pkg install --auto lux
raco pkg install --auto macrotypes-example
raco pkg install --auto macrotypes-lib
raco pkg install --auto magenc
raco pkg install --auto magnolisp
raco pkg install --auto make-log-interceptor
raco pkg install --auto map-widget
raco pkg install --auto marionette
raco pkg install --auto marionette-doc
raco pkg install --auto marionette-lib
raco pkg install --auto marionette-test
raco pkg install --auto markdown
raco pkg install --auto markparam
raco pkg install --auto markparam-doc
raco pkg install --auto markparam-lib
raco pkg install --auto markparam-test
raco pkg install --auto match-count
raco pkg install --auto match-plus
raco pkg install --auto match-string
raco pkg install --auto mboxrd-read
raco pkg install --auto mcfly
raco pkg install --auto measures
raco pkg install --auto measures-with-dimensions
raco pkg install --auto mediafile
raco pkg install --auto megaparsack
raco pkg install --auto megaparsack-doc
raco pkg install --auto megaparsack-lib
raco pkg install --auto megaparsack-parser
raco pkg install --auto megaparsack-parser-tools
raco pkg install --auto memcached
raco pkg install --auto memo
raco pkg install --auto memoize
raco pkg install --auto mf-apply
raco pkg install --auto midi-readwrite
raco pkg install --auto minikanren
raco pkg install --auto minipascal
raco pkg install --auto misc1
raco pkg install --auto mm
raco pkg install --auto mmap
raco pkg install --auto mobilpay
raco pkg install --auto mock
raco pkg install --auto mock-rackunit
raco pkg install --auto mode-lambda
raco pkg install --auto molis-hai
raco pkg install --auto monad
raco pkg install --auto monitors
raco pkg install --auto mordae
raco pkg install --auto morsel-doc
raco pkg install --auto morsel-lib
raco pkg install --auto mred-designer
raco pkg install --auto msgpack-rpc
raco pkg install --auto multi-id
raco pkg install --auto multicolumn
raco pkg install --auto multimethod
raco pkg install --auto multimethod-doc
raco pkg install --auto multimethod-lib
raco pkg install --auto multimethod-test
raco pkg install --auto multipath-daemon
raco pkg install --auto multiscope
raco pkg install --auto mumble-ping
raco pkg install --auto mutt
raco pkg install --auto my-cond
raco pkg install --auto namespaced-transformer
raco pkg install --auto namespaced-transformer-doc
raco pkg install --auto namespaced-transformer-lib
raco pkg install --auto nanopass
raco pkg install --auto neologia
raco pkg install --auto nested-hash
raco pkg install --auto net-ip
raco pkg install --auto net-ip-doc
raco pkg install --auto net-ip-lib
raco pkg install --auto net-ip-test
raco pkg install --auto net-jwt
raco pkg install --auto net2
raco pkg install --auto netrc
raco pkg install --auto neu-cs2500-handin
raco pkg install --auto neuron-lib
raco pkg install --auto nevermore
raco pkg install --auto no-vert-bar-lang
raco pkg install --auto north
raco pkg install --auto numformat-old
raco pkg install --auto numspell
raco pkg install --auto nvim-client
raco pkg install --auto ocelot
raco pkg install --auto open-app
raco pkg install --auto openal
raco pkg install --auto openh264-x86_64-macosx
raco pkg install --auto openweather
raco pkg install --auto operational-transformation
raco pkg install --auto operational-transformation-demo
raco pkg install --auto operational-transformation-lib
raco pkg install --auto opt
raco pkg install --auto option-bind
raco pkg install --auto org-mode
raco pkg install --auto osc
raco pkg install --auto overeasy
raco pkg install --auto package-analysis
raco pkg install --auto packet-socket
raco pkg install --auto Packrat
raco pkg install --auto parendown
raco pkg install --auto parendown-doc
raco pkg install --auto parendown-lib
raco pkg install --auto parendown-test
raco pkg install --auto parquet
raco pkg install --auto parsack
raco pkg install --auto parted
raco pkg install --auto pcg
raco pkg install --auto peg
raco pkg install --auto persistent-array
raco pkg install --auto persistent-union-find
raco pkg install --auto pfds
raco pkg install --auto phc-toolkit
raco pkg install --auto php-parser
raco pkg install --auto pict-abbrevs
raco pkg install --auto pidec
raco pkg install --auto pie
raco pkg install --auto pinyin
raco pkg install --auto pipe
raco pkg install --auto pitfall
raco pkg install --auto pkg-dep-draw
raco pkg install --auto pkg-index
raco pkg install --auto pkg-push
raco pkg install --auto plai-lazy
raco pkg install --auto plai-typed
raco pkg install --auto plai-typed-s-exp-match
raco pkg install --auto plaitypus
raco pkg install --auto plisqin
raco pkg install --auto plot-bestfit
raco pkg install --auto plot-container
raco pkg install --auto plt-build-plot
raco pkg install --auto plt-service-monitor
raco pkg install --auto plt-web
raco pkg install --auto plt-web-doc
raco pkg install --auto plt-web-lib
raco pkg install --auto pmap
raco pkg install --auto png-image
raco pkg install --auto point-free
raco pkg install --auto pollen
raco pkg install --auto pollen-citations-mcgill
raco pkg install --auto pollen-component
raco pkg install --auto pollen-count
raco pkg install --auto pollen-tfl
raco pkg install --auto pollen-tuftorial
raco pkg install --auto polyglot
raco pkg install --auto polyglot-doc
raco pkg install --auto polyglot-lib
raco pkg install --auto polyglot-test
raco pkg install --auto polysemy
raco pkg install --auto pop-pl
raco pkg install --auto poppler-i386-macosx
raco pkg install --auto poppler-win32-i386
raco pkg install --auto poppler-win32-x86-64
raco pkg install --auto poppler-x86-64-macosx
raco pkg install --auto port-match
raco pkg install --auto postfix-dot-notation
raco pkg install --auto postnet
raco pkg install --auto power-struct
raco pkg install --auto ppict
raco pkg install --auto ppict-slide-grid
raco pkg install --auto pprint
raco pkg install --auto pretty-format
raco pkg install --auto progedit
raco pkg install --auto protobj
raco pkg install --auto psd
raco pkg install --auto punctaffy
raco pkg install --auto punctaffy-lib
raco pkg install --auto punctaffy-test
raco pkg install --auto pure-crypto
raco pkg install --auto puresuri
raco pkg install --auto puzzler
raco pkg install --auto pvector
raco pkg install --auto python-tokenizer
raco pkg install --auto qiniu-sdk
raco pkg install --auto qresults-list
raco pkg install --auto quad
raco pkg install --auto quad-tree
raco pkg install --auto qualified-in
raco pkg install --auto Quaternion
raco pkg install --auto quickscript-extra
raco pkg install --auto quote-bad
raco pkg install --auto r-lexer
raco pkg install --auto r-linq
raco pkg install --auto r7rs
raco pkg install --auto r7rs-lib
raco pkg install --auto rackcheck
raco pkg install --auto racket-build-guide
raco pkg install --auto racket-cord
raco pkg install --auto racket-dogstatsd
raco pkg install --auto racket-immutable
raco pkg install --auto racket-language-server
raco pkg install --auto racket-quandl
raco pkg install --auto racket-route-match
raco pkg install --auto racket-scaffold
raco pkg install --auto racketcon-2018-web-devel-workshop
raco pkg install --auto racketmq
raco pkg install --auto racketscript
raco pkg install --auto racketscript-compiler
raco pkg install --auto racketscript-extras
raco pkg install --auto rackjure
raco pkg install --auto rackonsole
raco pkg install --auto rackterm
raco pkg install --auto rackunit-abbrevs
raco pkg install --auto rackunit-chk
raco pkg install --auto rackunit-fancy-runner
raco pkg install --auto rackunit-macrotypes-lib
raco pkg install --auto rackunit-spec
raco pkg install --auto raco-bug
raco pkg install --auto raco-macro-step
raco pkg install --auto racquel
raco pkg install --auto racr
raco pkg install --auto ragg
raco pkg install --auto ranked-programming
raco pkg install --auto rapider
raco pkg install --auto rapider-lib
raco pkg install --auto rash
raco pkg install --auto raw-string
raco pkg install --auto reactor
raco pkg install --auto readline-gpl
raco pkg install --auto rebellion
raco pkg install --auto recaptcha
raco pkg install --auto reconstruct-template
raco pkg install --auto redex-abbrevs
raco pkg install --auto redex-abbrevs-doc
raco pkg install --auto redex-abbrevs-lib
raco pkg install --auto redex-chk
raco pkg install --auto redex-parameter
raco pkg install --auto redis
raco pkg install --auto reed-solomon
raco pkg install --auto regex-machine
raco pkg install --auto Relation
raco pkg install --auto reloadable
raco pkg install --auto remember
raco pkg install --auto remix
raco pkg install --auto remote-shell
raco pkg install --auto remote-shell-doc
raco pkg install --auto remote-shell-lib
raco pkg install --auto repeated-application
raco pkg install --auto repltest
raco pkg install --auto reprovide-lang
raco pkg install --auto reprovide-lang-lib
raco pkg install --auto request
raco pkg install --auto require-typed-check
raco pkg install --auto response-ext
raco pkg install --auto retry
raco pkg install --auto rex
raco pkg install --auto rfc3339-old
raco pkg install --auto rfc6455
raco pkg install --auto ricoeur-kernel
raco pkg install --auto ring-buffer
raco pkg install --auto riposte
raco pkg install --auto rmacs
raco pkg install --auto rml-core
raco pkg install --auto rml-decisiontrees
raco pkg install --auto rml-knn
raco pkg install --auto rml-neural
raco pkg install --auto rockstar
raco pkg install --auto roman-numeral
raco pkg install --auto roomba
raco pkg install --auto rosette
raco pkg install --auto rosette-extras
raco pkg install --auto routy
raco pkg install --auto rpn
raco pkg install --auto ruckus
raco pkg install --auto russian
raco pkg install --auto rwind
raco pkg install --auto rws-html-template
raco pkg install --auto s-lib
raco pkg install --auto s3-sync
raco pkg install --auto sass
raco pkg install --auto scgi
raco pkg install --auto schema
raco pkg install --auto scope-operations
raco pkg install --auto scrapyard
raco pkg install --auto scratch
raco pkg install --auto scribble-abbrevs
raco pkg install --auto scribble-code-examples
raco pkg install --auto scribble-code-examples-lib
raco pkg install --auto scribble-math
raco pkg install --auto scribble-minted
raco pkg install --auto scripty
raco pkg install --auto scripty-doc
raco pkg install --auto scripty-lib
raco pkg install --auto scrypt
raco pkg install --auto sdraw
raco pkg install --auto search-upward
raco pkg install --auto secd
raco pkg install --auto semilit
raco pkg install --auto semver
raco pkg install --auto send-exp
raco pkg install --auto sentry
raco pkg install --auto sentry-doc
raco pkg install --auto sentry-lib
raco pkg install --auto sentry-test
raco pkg install --auto seq-no-order
raco pkg install --auto serial
raco pkg install --auto serialize-syntax-introducer
raco pkg install --auto set
raco pkg install --auto set-exp
raco pkg install --auto set-extras
raco pkg install --auto sexp-diff
raco pkg install --auto sha
raco pkg install --auto shell-pipeline
raco pkg install --auto shootout
raco pkg install --auto sicp
raco pkg install --auto signature
raco pkg install --auto simple-barcode
raco pkg install --auto simple-http
raco pkg install --auto simple-qr
raco pkg install --auto simple-svg
raco pkg install --auto simple-xlsx
raco pkg install --auto sinbad
raco pkg install --auto sl2014
raco pkg install --auto slack-api
raco pkg install --auto slideshow-pretty
raco pkg install --auto slideshow-repl
raco pkg install --auto sml
raco pkg install --auto snack
raco pkg install --auto soundex
raco pkg install --auto sparse
raco pkg install --auto spipe
raco pkg install --auto split-by
raco pkg install --auto spmatrix
raco pkg install --auto spvector
raco pkg install --auto sql
raco pkg install --auto sqlite-table
raco pkg install --auto srfi-lib-nonfree
raco pkg install --auto ss-rpc-server
raco pkg install --auto SSE
raco pkg install --auto ssh-hack
raco pkg install --auto staged-slide
raco pkg install --auto stardate
raco pkg install --auto static-rename
raco pkg install --auto static-rename-doc
raco pkg install --auto static-rename-lib
raco pkg install --auto static-rename-test
raco pkg install --auto statsd
raco pkg install --auto stomp
raco pkg install --auto stretchable-snip
raco pkg install --auto string-util
raco pkg install --auto stripe-integration
raco pkg install --auto struct-defaults
raco pkg install --auto struct-define
raco pkg install --auto struct-like-struct-type-property
raco pkg install --auto struct-update
raco pkg install --auto struct-update-doc
raco pkg install --auto struct-update-lib
raco pkg install --auto struct-update-test
raco pkg install --auto sudo
raco pkg install --auto suffixtree
raco pkg install --auto sugar
raco pkg install --auto superv
raco pkg install --auto sweet-exp
raco pkg install --auto sweet-exp-lib
raco pkg install --auto sweet-exp-test
raco pkg install --auto sxml
raco pkg install --auto sxml-intro
raco pkg install --auto syntax-class-or
raco pkg install --auto syntax-classes
raco pkg install --auto syntax-classes-doc
raco pkg install --auto syntax-classes-lib
raco pkg install --auto syntax-classes-test
raco pkg install --auto syntax-lang
raco pkg install --auto syntax-macro-lang
raco pkg install --auto syntax-parse-example
raco pkg install --auto syntax-warn
raco pkg install --auto syntax-warn-base
raco pkg install --auto syntax-warn-cli
raco pkg install --auto syntax-warn-doc
raco pkg install --auto syntax-warn-lang
raco pkg install --auto sysfs
raco pkg install --auto t-test
raco pkg install --auto tablesci
raco pkg install --auto tabular
raco pkg install --auto talk-typer
raco pkg install --auto tandem
raco pkg install --auto taskibble
raco pkg install --auto tasks
raco pkg install --auto temp-c
raco pkg install --auto temp-c-doc
raco pkg install --auto temp-c-lib
raco pkg install --auto template
raco pkg install --auto termios
raco pkg install --auto tesira
raco pkg install --auto tesseract
raco pkg install --auto test-more
raco pkg install --auto texmath
raco pkg install --auto text-table
raco pkg install --auto the-unicoder
raco pkg install --auto thread-utils
raco pkg install --auto threading
raco pkg install --auto threading-doc
raco pkg install --auto threading-lib
raco pkg install --auto thrift
raco pkg install --auto tightlight
raco pkg install --auto todo-list
raco pkg install --auto tomato-timer
raco pkg install --auto towers
raco pkg install --auto towers-lib
raco pkg install --auto towers-server
raco pkg install --auto tr-immutable
raco pkg install --auto trivial
raco pkg install --auto try
raco pkg install --auto try-racket-client
raco pkg install --auto tulip
raco pkg install --auto tulip-lib
raco pkg install --auto tulip-test
raco pkg install --auto turn-based-game
raco pkg install --auto turnstile
raco pkg install --auto turnstile-doc
raco pkg install --auto turnstile-example
raco pkg install --auto turnstile-lib
raco pkg install --auto turnstile-test
raco pkg install --auto twilio
raco pkg install --auto twixt
raco pkg install --auto txexpr
raco pkg install --auto txexpr-stxparse
raco pkg install --auto type-conventions
raco pkg install --auto type-expander
raco pkg install --auto typed-map
raco pkg install --auto typed-map-doc
raco pkg install --auto typed-map-lib
raco pkg install --auto typed-map-test
raco pkg install --auto typed-racket-stream
raco pkg install --auto typed-stack
raco pkg install --auto typed-struct-props
raco pkg install --auto typed-worklist
raco pkg install --auto typeset-rewriter
raco pkg install --auto tzdata
raco pkg install --auto tzgeolookup
raco pkg install --auto tzinfo
raco pkg install --auto udelim
raco pkg install --auto udev
raco pkg install --auto ulid
raco pkg install --auto unicode-properties
raco pkg install --auto unified-for
raco pkg install --auto unix-signals
raco pkg install --auto unlike-assets
raco pkg install --auto unlike-assets-lib
raco pkg install --auto unlike-assets-test
raco pkg install --auto unstable
raco pkg install --auto unstable-2d
raco pkg install --auto unstable-contract-lib
raco pkg install --auto unstable-debug-lib
raco pkg install --auto unstable-doc
raco pkg install --auto unstable-flonum-doc
raco pkg install --auto unstable-flonum-lib
raco pkg install --auto unstable-latent-contract-lib
raco pkg install --auto unstable-lib
raco pkg install --auto unstable-list-lib
raco pkg install --auto unstable-macro-testing-lib
raco pkg install --auto unstable-options-lib
raco pkg install --auto unstable-parameter-group-lib
raco pkg install --auto unstable-pretty-lib
raco pkg install --auto unstable-redex
raco pkg install --auto uri
raco pkg install --auto uri-old
raco pkg install --auto uri-template
raco pkg install --auto urlang
raco pkg install --auto uuid
raco pkg install --auto values-plus
raco pkg install --auto version-case
raco pkg install --auto vlc
raco pkg install --auto vulkan
raco pkg install --auto w3s
raco pkg install --auto wavelet-transform-haar-1d
raco pkg install --auto web-galaxy-doc
raco pkg install --auto web-galaxy-test
raco pkg install --auto webapi
raco pkg install --auto webscraperhelper
raco pkg install --auto whereis
raco pkg install --auto while-loop
raco pkg install --auto with-cache
raco pkg install --auto word
raco pkg install --auto wort
raco pkg install --auto x64asm
raco pkg install --auto x64asm-doc
raco pkg install --auto x64asm-lib
raco pkg install --auto xe
raco pkg install --auto xenomorph
raco pkg install --auto xexpr-path
raco pkg install --auto xfunctions-lib
raco pkg install --auto xlang
raco pkg install --auto xlist
raco pkg install --auto xml-html
raco pkg install --auto xmllint-win32-x86_64
raco pkg install --auto xmlns
raco pkg install --auto xsmith
raco pkg install --auto yaml
raco pkg install --auto yotsubAPI
raco pkg install --auto zeromq-r-lib
raco pkg install --auto zeromq-win32-i386
raco pkg install --auto zeromq-win32-x86_64
raco pkg install --auto zeromq-x86_64-linux-natipkg
raco pkg install --auto zippers
raco pkg install --auto zordoz
raco pkg install --auto zubat
